# Generated by Django 3.2.20 on 2023-10-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=15)),
            ],
        ),
    ]
